name: data_project_1
version: 1.0.0
config-version: 2
profile: data_project_1

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  data_project_1:
    # Materialize staging models as views, and marts as tables
    staging:
      +materialized: view
      +schema: staging
      +tags: ["staging"]
    marts:
      +materialized: table
      +schema: marts
      +tags: ["marts"]
