name: dbt_valenbisi

profile: dbt_valenbisi

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_valenbisi:
    # Materialize staging models as views, and marts as tables
    staging:
      +materialized: view
      +tags: ["staging"]
    marts:
      +materialized: table
