name: 'data_project_1'
version: '1.0'
config-version: 2
profile: 'data_project_1'

model-paths: ["models"]
target-path: "target"
clean-targets: ["target"]
vars:
  surrogate_key_treat_nulls_as_empty_strings: True

models:
  +materialized: view