data_project_1:
  target: dev
  outputs:
    dev:
      type: postgres
      host: db
      port: 5432
      user: postgres
      password: postgres
      dbname: data_project_1
      schema: public
      threads: 4