data_project_1:      # <-- Debe coincidir con "profile" en dbt_project.yml
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 4
      host: db                 # nombre del servicio de la base de datos en docker-compose
      port: 5432
      user: postgres
      password: postgres
      dbname: data_project_1
      schema: public
