data_project_1:
  target: dev
  outputs:
    dev:
      type: postgres
      host: db-1  
      user: postgres
      password: postgres
      port: 5432
      dbname: valenbisi_db   
      schema: public         
      threads: 4
