version: 2

models:
  - name: stg_air_quality_valencia
    description: >
      Datos de calidad del aire de Valencia, estandarizados y transformados de formato
      ancho (wide) a formato largo (long) para facilitar el análisis intermedio.
      Se realiza la limpieza inicial de nulos y valores atípicos.

    columns:
      - name: air_quality_pk
        description: Clave primaria (PK) única generada para cada fila (timestamp + location_id + pollutant_type).
        tests:
          - unique
          - not_null
      
      - name: location_id
        description: Identificador único de la estación de medición (OBJECTID original).
        tests:
          - not_null

      - name: station_name
        description: Nombre legible de la estación de calidad del aire.
      
      - name: station_address
        description: Dirección de la estación.
      
      - name: zona_type
        description: Tipo de zona donde se ubica la estación (e.g., urbana, industrial, etc.).

      - name: measurement_timestamp
        description: Fecha y hora exacta de la medición.
        tests:
          - not_null
      
      - name: longitude
        description: Longitud de la ubicación de la estación (columna LON original).
      
      - name: latitude
        description: Latitud de la ubicación de la estación (columna LAT original).

      - name: pollution_type
        description: Tipo de contaminante medido (resultado del despivotado).
        tests:
          - not_null
          - accepted_values:
              values: ['SO2', 'NO2', 'O3', 'CO', 'PM10', 'PM2.5', 'S02'] # Incluye S02 y SO2 por si hay typo en la fuente
              
      - name: concentratios_ug_m3
        description: Concentración del contaminante en microgramos por metro cúbico (ug/m3).
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0"
              
      - name: pollutant_category
        description: Clasificación del contaminante para agregación ('Particulates', 'Gases_Inorgánicos', 'Gases_Monóxido').
        tests:
          - not_null
          - accepted_values:
              values: ['Particulates', 'Gases_Inorgánicos', 'Gases_Monóxido', 'Otro']