version: 2

models:
  - name: stg_air_quality_valencia
    description: "Modelo staging para calidad del aire en Valencia"
    columns:
      - name: air_quality_pk
        description: "Clave primaria única para cada medición"
        tests:
          - unique
          - not_null
      - name: location_id
        description: "ID de la estación"
      - name: station_name
        description: "Nombre de la estación"
      - name: station_address
        description: "Dirección de la estación"
      - name: zona_type
        description: "Tipo de zona donde se encuentra la estación"
      - name: measurement_timestamp
        description: "Fecha y hora de la medición"
      - name: longitude
        description: "Longitud de la estación"
      - name: latitude
        description: "Latitud de la estación"
      - name: pollution_type
        description: "Tipo de contaminante"
      - name: concentration_ug_m3
        description: "Concentración del contaminante en µg/m³"
      - name: pollutant_category
        description: "Categoría del contaminante"
