
sources:
  - name: raw_data # Este nombre se usa como el primer argumento en {{ source() }}
    description: Datos crudos de las estaciones de la Agencia de Calidad del Aire de Valencia.
    
    # Asume que estos valores son los que usa la conexión 'dev' en tu profiles.yml
    database: pruebadb  # Nombre de la base de datos (según tu .env)
    schema: public     # Esquema donde se encuentra la tabla fuente
    
    tables:
      - name: estaciones # Este nombre se usa como el segundo argumento en {{ source() }}
        description: >
          Tabla con mediciones de calidad del aire en formato wide (SO2, NO2, O3, CO, PM10, PM25
          como columnas separadas). Contiene los datos brutos de las estaciones.
        
        columns:
          - name: objectid
            description: Identificador de la estación.
            tests:
              - not_null
          - name: fecha_carg
            description: Timestamp de la medición.
            tests:
              - not_null