version: 2

models:

  - name: mart_monthly_promedio
    description: "Mart mensual con promedios de contaminantes y promedio general."
    columns:
      - name: city
        description: "Ciudad de la estación."
      - name: nombre_estacion
        description: "Nombre de la estación."
      - name: fecha_month
        description: "Fecha truncada al mes."
      - name: no2_avg
        description: "Promedio mensual de NO2."
      - name: o3_avg
        description: "Promedio mensual de O3."
      - name: pm10_avg
        description: "Promedio mensual de PM10."
      - name: pm25_avg
        description: "Promedio mensual de PM2.5."
      - name: contaminacion_promedio
        description: "Promedio de los cuatro contaminantes para el mes."

  - name: mart_station_summary
    description: "Resumen por estación con promedios de contaminantes, primera y última medición y nivel de PM2.5."
    columns:
      - name: city
        description: "Ciudad donde se encuentra la estación."
      - name: nombre_estacion
        description: "Nombre de la estación."
      - name: first_measurement
        description: "Fecha del primer registro disponible para la estación."
      - name: last_measurement
        description: "Fecha del último registro disponible para la estación."
      - name: no2_avg
        description: "Promedio general de NO2 para la estación."
      - name: o3_avg
        description: "Promedio general de O3 para la estación."
      - name: pm10_avg
        description: "Promedio general de PM10 para la estación."
      - name: pm25_avg
        description: "Promedio general de PM2.5 para la estación."
      - name: nivel_pm25
        description: "Clasificación del nivel promedio de PM2.5: Bajo, Moderado o Alto."

  - name: mart_daily_promedio
    description: "Mart basado en int_daily_avg, con índice de contaminación, clasificación de NO2 y ranking de PM2.5."
    columns:
      - name: city
        description: "Ciudad de la estación."
      - name: nombre_estacion
        description: "Nombre de la estación."
      - name: fecha_day
        description: "Fecha truncada al día."
      - name: no2_avg
        description: "Promedio diario de NO2."
      - name: o3_avg
        description: "Promedio diario de O3."
      - name: pm10_avg
        description: "Promedio diario de PM10."
      - name: pm25_avg
        description: "Promedio diario de PM2.5."
      - name: indice_contaminacion
        description: "Promedio de los cuatro contaminantes para obtener un índice diario."
      - name: nivel_no2
        description: "Clasificación del nivel de NO2: Bajo, Moderado, Alto, Muy Alto."
      - name: ranking_pm25
        description: "Ranking diario de PM2.5 dentro de cada ciudad."
  
  - name: mart_hourly
    description: "Mart basado en int_hourly_avg, con índice de contaminación, clasificación de NO2 y ranking de PM2.5 por hora."
    columns:
      - name: city
        description: "Ciudad de la estación."
      - name: nombre_estacion
        description: "Nombre de la estación."
      - name: fecha_hour
        description: "Fecha truncada a la hora."
      - name: no2_avg
        description: "Promedio horario de NO2."
      - name: o3_avg
        description: "Promedio horario de O3."
      - name: pm10_avg
        description: "Promedio horario de PM10."
      - name: pm25_avg
        description: "Promedio horario de PM2.5."
      - name: indice_contaminacion
        description: "Promedio de los cuatro contaminantes para obtener un índice por hora."
      - name: nivel_no2
        description: "Clasificación del nivel de NO2: Bajo, Moderado, Alto, Muy Alto."
      - name: ranking_pm25
        description: "Ranking horario de PM2.5 dentro de cada ciudad."
 
  - name: mart_weekly_extended
    description: "Mart semanal basado en int_daily_avg, con promedios semanales, índice de contaminación y clasificación de NO2."
    columns:
      - name: city
        description: "Ciudad de la estación."
      - name: nombre_estacion
        description: "Nombre de la estación."
      - name: fecha_week
        description: "Fecha truncada al inicio de la semana."
      - name: no2_avg
        description: "Promedio semanal de NO2."
      - name: o3_avg
        description: "Promedio semanal de O3."
      - name: pm10_avg
        description: "Promedio semanal de PM10."
      - name: pm25_avg
        description: "Promedio semanal de PM2.5."
      - name: indice_contaminacion
        description: "Promedio de los cuatro contaminantes para generar un índice de contaminación semanal."
      - name: nivel_no2
        description: "Clasificación del nivel de NO2: Bajo, Moderado, Alto, Muy Alto."

  - name: mart_alerts
    description: "Mart que registra alertas cuando algún contaminante supera un umbral crítico."
    columns:
      - name: city
        description: "Ciudad de la estación."
      - name: nombre_estacion
        description: "Nombre de la estación."
      - name: fecha_hour
        description: "Fecha truncada a la hora."
      - name: no2_avg
        description: "Promedio horario de NO2."
      - name: o3_avg
        description: "Promedio horario de O3."
      - name: pm10_avg
        description: "Promedio horario de PM10."
      - name: pm25_avg
        description: "Promedio horario de PM2.5."
      - name: alerta
        description: "Indicador del tipo de alerta generado cuando un contaminante supera el umbral."

  - name: mart_fact_air_quality
    description: "Mart de fact table combinada con métricas diarias, semanales y mensuales por estación y ciudad."
    columns:
      - name: city
        description: "Ciudad de la estación."
      - name: nombre_estacion
        description: "Nombre de la estación."
      - name: fecha_day
        description: "Fecha diaria."
      - name: fecha_week
        description: "Fecha truncada al inicio de la semana."
      - name: fecha_month
        description: "Fecha truncada al mes."
      - name: daily_no2
        description: "Promedio diario de NO2."
      - name: daily_o3
        description: "Promedio diario de O3."
      - name: daily_pm10
        description: "Promedio diario de PM10."
      - name: daily_pm25
        description: "Promedio diario de PM2.5."
      - name: weekly_no2
        description: "Promedio semanal de NO2."
      - name: weekly_o3
        description: "Promedio semanal de O3."
      - name: weekly_pm10
        description: "Promedio semanal de PM10."
      - name: weekly_pm25
        description: "Promedio semanal de PM2.5."
      - name: monthly_no2
        description: "Promedio mensual de NO2."
      - name: monthly_o3
        description: "Promedio mensual de O3."
      - name: monthly_pm10
        description: "Promedio mensual de PM10."
      - name: monthly_pm25
        description: "Promedio mensual de PM2.5."

  - name: mart_top_polluted_stations
    description: "Mart que muestra el ranking de las estaciones más contaminadas por PM2.5 y PM10 diario."
    columns:
      - name: city
        description: "Ciudad de la estación."
      - name: nombre_estacion
        description: "Nombre de la estación."
      - name: fecha_day
        description: "Fecha diaria."
      - name: no2_avg
        description: "Promedio diario de NO2."
      - name: o3_avg
        description: "Promedio diario de O3."
      - name: pm10_avg
        description: "Promedio diario de PM10."
      - name: pm25_avg
        description: "Promedio diario de PM2.5."
      - name: rank_pm25
        description: "Ranking de PM2.5 por ciudad y día (1 = más contaminada)."
      - name: rank_pm10
        description: "Ranking de PM10 por ciudad y día (1 = más contaminada)."
