version: 2

sources:
  - name: raw_data
    database: data_project_1       # Cambia si tu DB tiene otro nombre
    schema: public                  # Cambia si tus tablas crudas están en otro schema
    tables:
      - name: estaciones
        description: "Tabla cruda con datos de calidad del aire y estaciones"



